environment:
  CYG_MIRROR: http://cygwin.mirror.constant.com
  BINTRAYAPIKEY:
    secure: uknPzww818XWJiLecwur9p1MfrkACOyx9d3iNrw/TuD89EoPSc8zLqKdPZjWdcQd
  matrix:
    - FLAVOR: squeak.sista.spur
      ARCH: win32x86
      CYG_ROOT: C:\cygwin
      CYG_SETUP: setup-x86.exe
      MINGW_ARCH: i686
    - FLAVOR: squeak.cog.spur
      ARCH: win32x86
      CYG_ROOT: C:\cygwin
      CYG_SETUP: setup-x86.exe
      MINGW_ARCH: i686
    - FLAVOR: squeak.cog.v3
      ARCH: win32x86
      CYG_ROOT: C:\cygwin
      CYG_SETUP: setup-x86.exe
      MINGW_ARCH: i686
    - FLAVOR: squeak.stack.spur
      ARCH: win32x86
      CYG_ROOT: C:\cygwin
      CYG_SETUP: setup-x86.exe
      MINGW_ARCH: i686
    - FLAVOR: squeak.stack.v3
      ARCH: win32x86
      CYG_ROOT: C:\cygwin
      CYG_SETUP: setup-x86.exe
      MINGW_ARCH: i686
    - FLAVOR: pharo.cog.spur
      ARCH: win32x86
      CYG_ROOT: C:\cygwin
      CYG_SETUP: setup-x86.exe
      MINGW_ARCH: i686
    - FLAVOR: newspeak.cog.spur
      ARCH: win32x86
      CYG_ROOT: C:\cygwin
      CYG_SETUP: setup-x86.exe
      MINGW_ARCH: i686
    - FLAVOR: newspeak.stack.spur
      ARCH: win32x86
      CYG_ROOT: C:\cygwin
      CYG_SETUP: setup-x86.exe
      MINGW_ARCH: i686
    - FLAVOR: squeak.cog.spur
      ARCH: win64x64
      CYG_ROOT: C:\cygwin64
      CYG_SETUP: setup-x86_64.exe
      MINGW_ARCH: x86_64
    - FLAVOR: pharo.cog.spur
      ARCH: win64x64
      CYG_ROOT: C:\cygwin64
      CYG_SETUP: setup-x86_64.exe
      MINGW_ARCH: x86_64
    - FLAVOR: squeak.stack.spur
      ARCH: win64x64
      CYG_ROOT: C:\cygwin64
      CYG_SETUP: setup-x86_64.exe
      MINGW_ARCH: x86_64
    - FLAVOR: pharo.stack.spur
      ARCH: win64x64
      CYG_ROOT: C:\cygwin64
      CYG_SETUP: setup-x86_64.exe
      MINGW_ARCH: x86_64

matrix:
  fast_finish: false

platform:
  - x86

clone_depth: 5

cache:
  - .thirdparty-cache

install:
  - ps: 'Start-FileDownload "http://cygwin.com/setup-x86.exe" -FileName "setup-x86.exe"'
  - ps: 'Start-FileDownload "http://cygwin.com/setup-x86_64.exe" -FileName "setup-x86_64.exe"'
  - '%CYG_SETUP% -dgnqNO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_ROOT%\var\cache\setup" -P mingw64-%MINGW_ARCH%-gcc-core,mingw64-%MINGW_ARCH%-gcc-g++,mingw64-%MINGW_ARCH%-headers,mingw64-%MINGW_ARCH%-runtime,zip,mingw64-%MINGW_ARCH%-clang,libiconv-devel,libglib2.0-devel,perl,mingw64-%MINGW_ARCH%-zlib,make,cmake,wget,mingw64-%MINGW_ARCH%-win-iconv'

build: false

# Cygwin build script
#
# NOTES:
#
# The stdin/stdout file descriptor appears not to be valid for the Appveyor
# build which causes failures as certain functions attempt to redirect
# default file handles. Ensure a dummy file descriptor is opened with 'exec'.
test_script:
  - '%CYG_ROOT%\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; exec ./.travis_build.sh"'
on_success:
  - '%CYG_ROOT%\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; exec ./.travis_deploy.sh"'
before_deploy:
  - '%CYG_ROOT%\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/deploy/pharo; exec 0</dev/null; exec ./filter-exec.sh pack-vm.sh"'
  - '%CYG_ROOT%\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/deploy/pharo; exec 0</dev/null; exec ./filter-exec.sh deploy-key.sh"'
deploy_script:
  - '%CYG_ROOT%\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; exec ./deploy/pharo/filter-exec.sh deploy-files.pharo.org.sh"'
